version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - .dbdate:/var/lib/postgresql